# Generated by Django 4.1.5 on 2023-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='reyting',
            field=models.FloatField(default=0),
        ),
    ]
