# Generated by Django 4.1.5 on 2023-02-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_mark_created_at_alter_mark_reyting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='reyting',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
